/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HRManagerRole;

import Business.Organization.HRManagerOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.LabTestWorkRequest;
import ReviewForm.ReviewForm;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.Instant;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author arihant
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    LabTestWorkRequest request;
    Organization organization;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessWorkRequestJPanel(JPanel userProcessContainer, Organization organization, LabTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.organization = organization;
        populateSolCombo();
    }

    public void populateSolCombo()
    {
       comboBoxSolution.addItem("Accused Fired");
       comboBoxSolution.addItem("Accused Under Trial");
       comboBoxSolution.addItem("No Action Taken");
       
//       for(ReviewForm review : organization.getReviewList().getReviewform_arraylist()){
//            System.out.println("came to process it");
//            System.out.println(request.getCompanyInfo() + " " + review.getOrg());
//            if(request.getCompanyInfo().toString().equals(review.getOrg().toString())){
//                System.out.println("1");
//                System.out.println(request.getCompanyInfo() + " " + review.getOrg());
//                if(request.getSender().equals(review.getEmployee())){
//                    System.out.println("2");
//                    System.out.println(request.getSender() + " " + review.getEmployee());
//                    if(review.getSubmit_status().equalsIgnoreCase("Pending 1")){
////                        review.setSubmit_status("Submit 1");
//                        System.out.println("Successfull");
//                    }
//                }
//            }
//          
//        }
//        System.out.println("end");
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        comboBoxSolution = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(0, 204, 204));

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Result");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backJButton)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(submitJButton)
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(comboBoxSolution, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxSolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(submitJButton))
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        HRManagerWorkAreaJPanel hrmwajp = (HRManagerWorkAreaJPanel) component;
        hrmwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        for(ReviewForm review : organization.getReviewList().getReviewform_arraylist()){
            if(request.getCompanyInfo().toString().equals(review.getOrg().toString())){
                if(request.getSender().equals(review.getEmployee())){
                    if(review.getSubmit_status().equalsIgnoreCase("Pending 1")){
                        review.setSubmit_status("Submit 1");
                    }
                }
            }
          
        }
        
        request.setTestResult((String) comboBoxSolution.getSelectedItem());
        request.setStatus("Completed");
        request.setResolveDate(Date.from(Instant.now()));
        JOptionPane.showMessageDialog(null,"Request Completed");
    }//GEN-LAST:event_submitJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox comboBoxSolution;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables
}
