/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirlines;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author arihant
 */
public class CreateNewAirlinersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewAirliners
     */
    JPanel panel;

    public CreateNewAirlinersJPanel(JPanel panel) {
        initComponents();
        this.panel = panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Create New Airliners");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 11, -1, -1));

        jLabel2.setText("Airliners Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 86, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 83, 126, -1));

        jLabel3.setText("Other Fields");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 130, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 127, 126, -1));

        jButton1.setText("Create Airliners");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 180, -1, -1));

        jButton2.setText("<<back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 253, -1, -1));

        jButton3.setText("Add Flights");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 253, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        panel.remove(this);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.previous(panel);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
