/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ITDepartmentRole;

import Business.Enterprise.Enterprise;
import Business.Organization.DoctorAdmin;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import ReviewForm.ReviewForm;
import UserInterface.Doctor.Test;
import UserInterface.Doctor.TestRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arihant
 */
public class DrugTest extends javax.swing.JPanel {

    /**
     * Creates new form DrugTest
     */
    JPanel panel;
    UserAccount ua;
    Organization org;
    Enterprise enterprise;
    public DrugTest(JPanel panel, UserAccount useracc, Organization org, Enterprise enterprise) {
        initComponents();
        this.panel = panel;
        this.ua = useracc;
        this.org = org;
        this.enterprise = enterprise;
        populateTable();
    }

    public void populateTable(){
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
        for(Test test : organization.getTestList().getTest_list()){
            if(test.getOrganization() == org){
            DefaultTableModel dtm = (DefaultTableModel) test_status.getModel();
            dtm.setRowCount(0);
            Object [] row = new Object[2];
            row[0] = test.getStatus();
            row[1] = test.getResult_test();
            dtm.addRow(row);}
        }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        test_result = new javax.swing.JTable();
        back = new javax.swing.JButton();
        report = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        test_status = new javax.swing.JTable();
        taketest = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        test_result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Blood", "Urine", "Hair", "Proxyphene", "Prescription 1", "Prescription 2"
            }
        ));
        jScrollPane1.setViewportView(test_result);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 590, 90));

        back.setBackground(new java.awt.Color(153, 0, 0));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 60, -1));

        report.setText("Reports");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        test_status.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Status", "Result"
            }
        ));
        jScrollPane2.setViewportView(test_status);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 590, 90));

        taketest.setText("Take Test");
        taketest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taketestActionPerformed(evt);
            }
        });
        add(taketest, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        panel.remove(this);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.previous(panel);
    }//GEN-LAST:event_backActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            for(Test test : organization.getTestList().getTest_list()){
                if(test.getOrganization() == org){
                    DefaultTableModel dtm = (DefaultTableModel) test_result.getModel();
                    dtm.setRowCount(0);
                    Object [] row = new Object[6];
                    row[0] = test.getBlood_test();
                    row[1] = test.getUrine_test();
                    row[2] = test.getHair_test();
                    row[3] = test.getProxyphene();
                    row[4] = test.getPriscription1();
                    row[5] = test.getPriscription2();
                    dtm.addRow(row);}
            }
        }
    }//GEN-LAST:event_reportActionPerformed

    private void taketestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taketestActionPerformed
        TestRequest request = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            for(Test test : organization.getTestList().getTest_list()){
                if(test.getEmployee() == ua && test.getStatus().equals("pending")){
                    JOptionPane.showMessageDialog(null, "Wait for the earlier Request to Finish");
                }
                else{
                    request = new TestRequest();
                    request.setOrganization(org);
                    request.setEmployee(ua);
                    if(request.getStatus() == null){
                        request.setStatus("Pending");
                        request.setEmp_status("Due");
                    }
                    
                    
                }
            }
        }
        if(request != null){
            for (Organization organizationn : enterprise.getOrganizationDirectory().getOrganizationList()){
                if (organizationn instanceof DoctorAdmin ){
                    organizationn.getTestList().getTest_list().add(request);
                }
            }
            JOptionPane.showMessageDialog(null, "Request Submitted.");
        }
        
        System.out.println("trying now");
        populateTable();
    }//GEN-LAST:event_taketestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton report;
    private javax.swing.JButton taketest;
    private javax.swing.JTable test_result;
    private javax.swing.JTable test_status;
    // End of variables declaration//GEN-END:variables
}
