/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ITDepartmentRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.HRManagerOrganization;
import Business.Organization.DoctorAdmin;
import Business.Organization.ITDepartmentOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import ReviewForm.Form;
import ReviewForm.FormQueue;
import UserInterface.Doctor.TestRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author arihant
 */
public class ITWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ITWorkAreaJPanel
     */
     private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private Organization organization;
    private ITDepartmentOrganization iTDepartmentOrganization;
    private Enterprise enterprise;
    public ITWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account; //hondait
        this.system = business;
        this.enterprise = enterprise;
        this.organization = organization; // it dept organization
        this.iTDepartmentOrganization= (ITDepartmentOrganization) organization;
        valueLabel.setText(enterprise.getName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComplaint = new javax.swing.JButton();
        btnDrugTest = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        departmentlabel = new javax.swing.JLabel();
        claimcompensation = new javax.swing.JButton();
        Reviews = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComplaint.setText("Register A Complaint");
        btnComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplaintActionPerformed(evt);
            }
        });
        add(btnComplaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        btnDrugTest.setText("Drug Test");
        btnDrugTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrugTestActionPerformed(evt);
            }
        });
        add(btnDrugTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 140, -1));
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 130, 26));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 30));

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Department:");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 30));
        add(departmentlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 130, 26));

        claimcompensation.setText("Claim Compensation");
        claimcompensation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claimcompensationActionPerformed(evt);
            }
        });
        add(claimcompensation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 130, -1));

        Reviews.setText("Reviews");
        Reviews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewsActionPerformed(evt);
            }
        });
        add(Reviews, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplaintActionPerformed
        // TODO add your handling code here:
        ITDepartmentComplaintWorkAreaJPanel itdcwajp  = new ITDepartmentComplaintWorkAreaJPanel(userProcessContainer,userAccount,iTDepartmentOrganization,system,enterprise);
        userProcessContainer.add("ITDepartmentComplaintWorkAreaJPanel" , itdcwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnComplaintActionPerformed

    private void btnDrugTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrugTestActionPerformed
        DrugTest test = new DrugTest(userProcessContainer, userAccount, iTDepartmentOrganization, enterprise);
        userProcessContainer.add("DrugTest", test);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDrugTestActionPerformed

    private void claimcompensationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claimcompensationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claimcompensationActionPerformed

    private void ReviewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewsActionPerformed
        FormQueue formqueue = new FormQueue(userProcessContainer, iTDepartmentOrganization, organization, enterprise, userAccount);
        userProcessContainer.add("FormQueue", formqueue);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ReviewsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reviews;
    private javax.swing.JButton btnComplaint;
    private javax.swing.JButton btnDrugTest;
    private javax.swing.JButton claimcompensation;
    private javax.swing.JLabel departmentlabel;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
