/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReviewForm;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arihant
 */
public class FormQueue extends javax.swing.JPanel {

    /**
     * Creates new form FormQueue
     */
    JPanel panel;
    Organization self_organization;
    Organization organization;
    Enterprise enterprise;
    ReviewForm req;
    UserAccount ua;
    
    public FormQueue(JPanel panel, Organization my_organization, Organization tot_organization, Enterprise enterprise, UserAccount ua) {
        initComponents();
        this.panel = panel;
        this.organization = tot_organization;
        this.self_organization = my_organization;
        this.ua = ua;
        this.enterprise = enterprise;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)employeereviewqueue.getModel();
        model.setRowCount(0);
        
        for(ReviewForm request : organization.getReviewList().getReviewform_arraylist()){
            System.out.println("P1 " + request.getPerformance1());
            System.out.println("P2 " + request.getPerformance2());
            if(request.getSubmit_status() == null || request.getSubmit_status().equalsIgnoreCase("Submit 2")){
                continue;
            }
            else{
                req = request;
                Object[] row = new Object[2];
                System.out.println(request.getSubmit_status());
                row[0] = request.getOrg();
                row[1] = request.getEmployee();
                model.addRow(row);
            }
            
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        employeereviewqueue = new javax.swing.JTable();
        submitresponse = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeereviewqueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Organization", "Employee"
            }
        ));
        jScrollPane1.setViewportView(employeereviewqueue);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 90));

        submitresponse.setText("Submit Response");
        submitresponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitresponseActionPerformed(evt);
            }
        });
        add(submitresponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        back.setBackground(new java.awt.Color(153, 0, 0));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitresponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitresponseActionPerformed
        
        int selectedRow = employeereviewqueue.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "please select the entry");
            return;
        }
        Object org = employeereviewqueue.getValueAt(selectedRow, 0);
        Object emp = employeereviewqueue.getValueAt(selectedRow, 1);
        
        for(ReviewForm request : organization.getReviewList().getReviewform_arraylist()){
            System.out.println(request.getOrg() + " " + request.getEmployee());
            Organization orgg = request.getOrg();
            if(org == orgg){
                UserAccount empp = request.getEmployee();
                if(emp == empp){
                    Form reviewform = new Form(panel, organization, orgg, empp, enterprise, req, ua);
                    panel.add("Form", reviewform);
                    CardLayout layout = (CardLayout) panel.getLayout();
                    layout.next(panel);
                }
            }
        }
        
        
    }//GEN-LAST:event_submitresponseActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        panel.remove(this);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.previous(panel);
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTable employeereviewqueue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitresponse;
    // End of variables declaration//GEN-END:variables
}
