/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.MarketingDepartmentRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.MarketingDepartmentOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import ReviewForm.Form;
import ReviewForm.FormQueue;
import UserInterface.ITDepartmentRole.DrugTest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author arihant
 */
public class MarketingWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MarketingWorkAreaJPanel
     */
        private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;
    private MarketingDepartmentOrganization marketingDepartmentOrganization;
    private Enterprise enterprise;
    public MarketingWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, EcoSystem business, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.organization = organization;
        this.enterprise = enterprise;
        this.marketingDepartmentOrganization = (MarketingDepartmentOrganization) organization;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnComplaint = new javax.swing.JButton();
        btnDrugTest = new javax.swing.JButton();
        submitreview = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 127, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 35, 158, 26));

        btnComplaint.setText("Register A Complaint");
        btnComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplaintActionPerformed(evt);
            }
        });
        add(btnComplaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 140, -1));

        btnDrugTest.setText("Take a Drug Test");
        btnDrugTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrugTestActionPerformed(evt);
            }
        });
        add(btnDrugTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 140, -1));

        submitreview.setText("Submit Review");
        submitreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitreviewActionPerformed(evt);
            }
        });
        add(submitreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplaintActionPerformed
        // TODO add your handling code here:
        MarketingDepartmentComplaintWorkAreaJPanel mdcwajp  = new MarketingDepartmentComplaintWorkAreaJPanel(userProcessContainer,userAccount,marketingDepartmentOrganization,business,enterprise, organization);
        userProcessContainer.add("MarketingDepartmentComplaintWorkAreaJPanel" , mdcwajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnComplaintActionPerformed

    private void btnDrugTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrugTestActionPerformed
        DrugTest test = new DrugTest(userProcessContainer, userAccount, marketingDepartmentOrganization, enterprise);
        userProcessContainer.add("DrugTest", test);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDrugTestActionPerformed

    private void submitreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitreviewActionPerformed
        FormQueue queue = new FormQueue(userProcessContainer, marketingDepartmentOrganization, organization, enterprise, userAccount);
        userProcessContainer.add("FormQueue", queue);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_submitreviewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComplaint;
    private javax.swing.JButton btnDrugTest;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton submitreview;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
