/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.MarketingDepartmentRole;

import UserInterface.ITDepartmentRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 *
 * @author arihant
 */

import Business.EcoSystem;

import Business.Enterprise.Enterprise;
import Business.Organization.HRManagerOrganization;
import Business.Organization.ITDepartmentOrganization;
import Business.Organization.MarketingDepartmentOrganization;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.network.Network;
import ReviewForm.ReviewRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.security.Provider;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
public class MrRequestComplaintJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestComplaintJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    private Organization organization;

   public MrRequestComplaintJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EcoSystem business, Organization organization) {

    initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount =  userAccount;
        this.business = business;
        this.organization = organization;
        valueLabel.setText(enterprise.getName());
        populateComboBox();
        populateComplaintTypeComboBox();
  
    }
   
    public void populateComboBox()
    {
          for(Organization organization: enterprise.getOrganizationDirectory().getOrganizationList()){
              if(!(organization instanceof HRManagerOrganization))
              {             
              for(UserAccount userAccount1:organization.getUserAccountDirectory().getUserAccountList()){
               if((!userAccount1.equals(userAccount))==false){
                   
               }
               else{
                 comboBoxCompAgainst.addItem(userAccount1);
               }            
           }
              }     

       } 
    }
    
     public void populateComplaintTypeComboBox()
    {
        comboBoxCompType.addItem("Racisist Offence");
        comboBoxCompType.addItem("Sexual Offence");
        comboBoxCompType.addItem("Gender based offence");
        comboBoxCompType.addItem("Other");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        comboBoxCompAgainst = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxCompType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtTeam = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setText("Send Request ");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 310, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 24, 120, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 34, 125, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 310, -1, -1));

        jLabel1.setText("Message");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 110, -1, -1));
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 107, 170, -1));

        add(comboBoxCompAgainst, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 157, 170, -1));

        jLabel3.setText("complaint Against");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 160, -1, -1));

        jLabel4.setText("Complaint Type");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 202, -1, -1));

        add(comboBoxCompType, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 199, 170, -1));

        jLabel2.setText("manager");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 237, 84, 17));
        add(txtTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 237, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        String message = messageJTextField.getText();
        String manager = txtTeam.getText();
        
        LabTestWorkRequest request = new LabTestWorkRequest();
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");
        request.setComplaintAgainst((UserAccount) comboBoxCompAgainst.getSelectedItem());
        request.setComplaintType((String) comboBoxCompType.getSelectedItem());
        request.setCompanyInfo(organization.toString());
        request.setManager(manager);
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof HRManagerOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        
        ReviewRequest reviewreq = new ReviewRequest();
        reviewreq.setOrg(organization);
        reviewreq.setEmployee(userAccount);
        if(reviewreq.getSubmit_status() == null)
            reviewreq.setSubmit_status("Pending 1");
        
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            
            if (organization instanceof HRManagerOrganization){
                organization.getReviewList().getReviewform_arraylist().add(reviewreq);
            }
            if (organization instanceof ITDepartmentOrganization){
                organization.getReviewList().getReviewform_arraylist().add(reviewreq);
            }
            if (organization instanceof MarketingDepartmentOrganization){
                organization.getReviewList().getReviewform_arraylist().add(reviewreq);
            }
        }
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MarketingDepartmentComplaintWorkAreaJPanel mr = (MarketingDepartmentComplaintWorkAreaJPanel) component;
        mr.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox comboBoxCompAgainst;
    private javax.swing.JComboBox comboBoxCompType;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTextField txtTeam;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
