/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Business.Agent;
import Business.Airline;
import Business.Airline_Access;
import Business.Customer;
import FlightSchedule.ContinueBookingJPanel;
import UserInterface.ManageAirliners.CreateNewAirlinerFlightsJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arihant
 */
public class SearchBestDeals extends javax.swing.JPanel {

    /**
     * Creates new form SearchBestDeals
     */
    JPanel panel;
    private Agent agent;
    private Customer cust = new Customer();
    public SearchBestDeals(JPanel cardlayout, Agent agent) {
        this.panel = cardlayout;
        this.agent = agent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        time = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        resulttable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        airline = new javax.swing.JTextField();
        deals = new javax.swing.JButton();
        book = new javax.swing.JButton();

        jLabel1.setText("Price");

        jLabel2.setText("Time");

        time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning", "Day", "Night" }));

        resulttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner", "Model No.", "From", "To", "Time", "Best Price", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(resulttable);

        jLabel3.setText("RESULTS:");

        jLabel4.setText("Airline");

        deals.setText("Show Deals");
        deals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealsActionPerformed(evt);
            }
        });

        book.setText("Book");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deals)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(airline, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(book)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(airline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deals)
                        .addGap(24, 24, 24)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(book)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealsActionPerformed
        inc:
        try{
        int amount = Integer.parseInt(price.getText());
        String tym = time.getSelectedItem().toString();
        String air = airline.getText();
        DefaultTableModel dtm = (DefaultTableModel)resulttable.getModel();
        dtm.setRowCount(0);
        int [] cost = new int[3];
        int bestprice = 100000;
        for(Airline airplane : agent.getAirplane()){
            
                if((airplane.getWin_cost() < amount || airplane.getMid_cost() < amount || airplane.getAis_cost() < amount) && airplane.getTime().equals(tym) && airplane.getAirline().equals(air)){
                Object row[] = new Object[7];
                row[0] = airplane.getAirline();
                row[1] = airplane.getModelNo();
                row[2] = airplane.getSource();
                row[3] = airplane.getDestination();
                row[4] = airplane.getTime();
                cost[0] = airplane.getWin_cost();
                cost[1] = airplane.getMid_cost();
                cost[2] = airplane.getAis_cost();
                for(int i = 0; i < 3; i++){
                    for(int j = 1; j < 2; j++){
                        if(cost[i] < cost[j]){
                            if(cost[i] < bestprice)
                                bestprice = cost[i];
                        }                        
                        else if(cost[j] < bestprice)
                                bestprice = cost[j];
                    }
                }
                row[5] = bestprice;
                row[6] = airplane.getTotal_seats() - airplane.getBooked();
                dtm.addRow(row);
                }
                else{
                }
            }
            
        }catch(Exception e){
            break inc;
            }
    }//GEN-LAST:event_dealsActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)resulttable.getModel();        
        try{
        int row = resulttable.getSelectedRow();
        String book_method = "SELF";
        String custid = JOptionPane.showInputDialog("Enter Customer ID");
        cust.setCustId(custid);
        String flight = resulttable.getModel().getValueAt(row, 1).toString();
        ContinueBookingJPanel booking = new ContinueBookingJPanel(panel, agent, custid, book_method);
        booking.setFlight(flight);
        booking.setdata();
        panel.add("ContinueBookingJPanel", booking);
        CardLayout layout = (CardLayout)panel.getLayout();
        layout.next(panel);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_bookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airline;
    private javax.swing.JButton book;
    private javax.swing.JButton deals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price;
    private javax.swing.JTable resulttable;
    private javax.swing.JComboBox<String> time;
    // End of variables declaration//GEN-END:variables
}
