/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Agent;
import Business.Airline;
import Business.Airline_Access;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author arihant
 */
public class CreateNewAirlinersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewAirliners
     */
    JPanel panel;
    private Agent agent;
    String airline_name;
    public CreateNewAirlinersJPanel(JPanel panel, Agent agent) {
        initComponents();
        this.panel = panel;
        this.agent = agent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        airliner = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Create New Airliner");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 11, -1, -1));

        jLabel2.setText("Airliners Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 86, -1, -1));
        add(airliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 83, 126, -1));

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        back.setText("<<back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
        panel.remove(this);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.previous(panel);
    }//GEN-LAST:event_backActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        Airline air = agent.addairplane();
        try{
            airline_name = airliner.getText();
            if(airline_name.isEmpty())
                JOptionPane.showMessageDialog(null, "Can't Add");
            else{
                air.setAirline(airline_name);
                JOptionPane.showMessageDialog(null, "Airline Added to Directory");
                CreateNewAirlinerFlightsJPanel create = new CreateNewAirlinerFlightsJPanel(panel, agent);
                create.visible();
                create.setData(airline_name);
                panel.add("CreateNewAirlinerFlightsJPanel", create);
                CardLayout layout = (CardLayout)panel.getLayout();
                layout.next(panel);
                
            }
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_createActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airliner;
    private javax.swing.JButton back;
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
