/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Agent;
import Business.Airline;
import Business.Airline_Access;
import FlightSchedule.ManageFlightsJPanel;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arihant
 */
public class ManageAirlinersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinersJPanel
     */
    private JPanel panel;
    private Agent agent;
    Object [] row;
    public ManageAirlinersJPanel(JPanel cardSequenceJPanel, Agent agent) {
        this.panel = cardSequenceJPanel;
        this.agent = agent;
        initComponents();
        populate();
    }
    
    public void populate(){
        DefaultTableModel dtm = (DefaultTableModel)airlinelist.getModel();
        dtm.setColumnCount(0);
        row = agent.getairlinedetails();
        dtm.addColumn("Airline", row);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newairliner = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        go = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        airlinename = new javax.swing.JTextField();
        bookings = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        airlinelist = new javax.swing.JTable();
        getflights = new javax.swing.JButton();

        newairliner.setText("New Airliner>>");
        newairliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newairlinerActionPerformed(evt);
            }
        });

        jLabel1.setText("Manage Airliner");

        jLabel2.setText("Airliner Name");

        go.setText("Go");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        bookings.setText("Bookings");
        bookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingsActionPerformed(evt);
            }
        });

        airlinelist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(airlinelist);

        getflights.setText("Select");
        getflights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getflightsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(getflights, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newairliner)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bookings)
                                    .addComponent(airlinename, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(go)
                                    .addComponent(refresh)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getflights))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(go)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airlinename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newairliner)
                    .addComponent(refresh)
                    .addComponent(bookings))
                .addContainerGap(217, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newairlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newairlinerActionPerformed
        CreateNewAirlinersJPanel create = new CreateNewAirlinersJPanel(panel, agent);
        panel.add("CreateNewAirlinerJPanel", create);
        CardLayout layout = (CardLayout)panel.getLayout();
        layout.next(panel);
        
    }//GEN-LAST:event_newairlinerActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
       
        try{String name = airlinename.getText();
        DefaultTableModel dtm = (DefaultTableModel)airlinelist.getModel();
        dtm.setRowCount(0);
        for(int i =0; i< row.length-1;i++){
            if(row[i].equals(name)){
                Object [] data = new Object[1];
                data[0] = row[i];
                dtm.addRow(data);
            }
        }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_goActionPerformed

    private void bookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingsActionPerformed
        BookingsDetail detail = new BookingsDetail(panel, agent);
        panel.add("BookingsDetail", detail);
        CardLayout layout  = (CardLayout)panel.getLayout();
        layout.next(panel);
    }//GEN-LAST:event_bookingsActionPerformed

    private void getflightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getflightsActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)airlinelist.getModel();        
        try{
        int row = airlinelist.getSelectedRow();       
        String name = airlinelist.getModel().getValueAt(row, 0).toString();
        ManageFlightsJPanel update = new ManageFlightsJPanel(panel, name, agent);
        panel.add("ManageFlightsJPanel", update);
        CardLayout layout = (CardLayout) panel.getLayout();
        layout.next(panel);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_getflightsActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        populate();
    }//GEN-LAST:event_refreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airlinelist;
    private javax.swing.JTextField airlinename;
    private javax.swing.JButton bookings;
    private javax.swing.JButton getflights;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton newairliner;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
