/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTravel;

import Business.Agent;
import Business.Airline;
import FlightSchedule.ContinueBookingJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arihant
 */
public class TravelSearch extends javax.swing.JPanel {

    /**
     * Creates new form TravelSearch
     */
    private Agent agent;
    JPanel panel;
    public TravelSearch(JPanel panel, Agent agent) {
        this.panel = panel;
        this.agent = agent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        source = new javax.swing.JTextField();
        destination = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        agenttable = new javax.swing.JTable();
        book = new javax.swing.JButton();

        jLabel1.setText("Source");

        jLabel2.setText("Destination");

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        agenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline", "Flight No.", "Time", "Availability", "Best Price"
            }
        ));
        jScrollPane1.setViewportView(agenttable);

        book.setText("Book");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(search)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(source, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addComponent(book))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(search)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(book)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        try{String src = source.getText();
        String dest = destination.getText();
        DefaultTableModel dtm = (DefaultTableModel)agenttable.getModel();
        dtm.setRowCount(0);
        int [] cost = new int[3];
        int bestprice = 100000;
        for(Airline air : agent.getAirplane()){
            if(air.getSource().equals(src) && air.getDestination().equals(dest)){
                Object [] row = new Object[5];
                row[0] = air.getAirline();
                row[1] = air.getModelNo();
                row[2] = air.getTime();
                row[3] = air.getTotal_seats() - air.getBooked();
                cost[0] = air.getWin_cost();
                cost[1] = air.getMid_cost();
                cost[2] = air.getAis_cost();
                for(int i = 0; i < 3; i++){
                    for(int j = 1; j < 2; j++){
                        if(cost[i] < cost[j]){
                            if(cost[i] < bestprice)
                                bestprice = cost[i];
                        }                        
                        else if(cost[j] < bestprice)
                                bestprice = cost[j];
                    }
                }
                row[4] = bestprice;
                dtm.addRow(row);
            }
            else{
            }
        }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_searchActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)agenttable.getModel();        
        
        try{
        int row = agenttable.getSelectedRow();
        String book_method = "AGENT";
        String custid = JOptionPane.showInputDialog("Enter Customer ID");
        String flight = agenttable.getModel().getValueAt(row, 1).toString();
        ContinueBookingJPanel booking = new ContinueBookingJPanel(panel, agent, custid, book_method);
        booking.setFlight(flight);
        booking.setdata();
        panel.add("ContinueBookingJPanel", booking);
        CardLayout layout = (CardLayout)panel.getLayout();
        layout.next(panel);
        }catch(Exception e){
                }
    }//GEN-LAST:event_bookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable agenttable;
    private javax.swing.JButton book;
    private javax.swing.JTextField destination;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search;
    private javax.swing.JTextField source;
    // End of variables declaration//GEN-END:variables
}
